name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /opt/tusabot
          git pull origin main
          
          sudo systemctl stop tusabot tusabot-api tusabot-web || true
          
          source venv/bin/activate
          pip install -r requirements.txt
          
          source .env
          export PGPASSWORD="${DB_PASSWORD}"
          psql -h ${DB_HOST} -U ${DB_USER} -d ${DB_NAME} -f migrations/001_initial_schema.sql || true
          
          cd project
          npm install
          npm run build
          cd ..
          
          sudo systemctl start tusabot tusabot-api tusabot-web
          echo "✅ Deployment completed!"