name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 5.129.250.86
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /opt/tusabot
          git pull origin main
          pkill -f bot.py || true
          pkill -f api.py || true
          pip3 install -r requirements.txt
          python3 bot.py &
          python3 api.py &
          echo "✅ Деплой завершен!"